### PR TITLE
fixing executability

### PR DESCRIPTION
**Pull request by behrisch**

### CODE REVIEW

**Review by abrac — COMMENTED** [review]
Did you just do `chmod +x` on these files? I.e. so that they can be executable on Linux. I'm asking because Github shows nothing in the diff, though you obviously did change something.

**Comment by behrisch** [comment]
Yes, that's what I did.

**Comment by behrisch** [comment]
For your information: We plan to do a new SUMO release on 2020-09-08 and the rpms we create complained about the scripts not having the executable flag.

**Comment by lcodeca** [comment]
I usually keep it off so people are forced to call it with python3 something.py
Thank you for the info.

**Comment by behrisch** [comment]
If you want that, then you should omit the shebang header "!#". Then the rpm build will not complain.

**Pull request merged**
